### ISSUE TITLE
To fix : IA not sending message codes anymore

### ISSUE THREAD

**Issue by Sindarus** [Sindarus/tsumegomaker#19]
Commit https://github.com/Sindarus/tsumegomaker/commit/0f4e7758ff9af0316866a681a1b13cbc9a9481ef inserted a bug where the IA raises an error and does not return the message associated with the move. When the user wins problem 1, for example, they get a "erreur IA move". Maybe this could be the opportunity to change and decide how the messages are stored in the SGF. Should they only be set on player's move ? only on IA's move ?

**Comment by Yoz0** [comment]
We have already decided that message could go on IA or Player move, as long as it's the last move. I have undone the commit who introduced the bug.

**Comment by Sindarus** [comment]
Though, shouldn't the AI raise an error when it doesn't know what to play, instead of defaulting to a pass ? In case there's no registered answer to a given move in the SGF and we're trying to debug, I think this behavior could lead us to think the IA reads a "pass" from the SGF file, whereas it is just defaulting.

**Comment by Yoz0** [comment]
Hmmm... The AI shouldn't raise an error, because sometime the game ends after the player move. With that said, it's not normal that the function ia_sgf.play() "apply" the move on the sgf tree... This should be made differently. It will when we'll have the websockets implemented.
